# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9da92750ad2a26c438c6ace09e494b2dce45f7e0022b010701e30cdd66710dbcd7d636a02182ef505c9a3ac4142559fb5575dd62207106b41586c0348d283b

test:
  secret_key_base: 4fb7097800492f21e6f7c3bac288a34038ec48f700eb42a9b9c4facaf32720782f0475dd591b91b3876152def37ff2c5de0c1062c2ec5ebe1d1eef9d24bec52c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6de4e91248746449ddda58455a5899b5927124ce10e2695299360c540a0056fa9f52f97216c04f59c293f5481dd6981f4b60eb49e5504749a1855d97c163b88f
